// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod kline {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum KlineDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KlineData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for KlineData<'a> {
  type Inner = KlineData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> KlineData<'a> {
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 4;
  pub const VT_OPEN: flatbuffers::VOffsetT = 6;
  pub const VT_HIGH: flatbuffers::VOffsetT = 8;
  pub const VT_LOW: flatbuffers::VOffsetT = 10;
  pub const VT_CLOSE: flatbuffers::VOffsetT = 12;
  pub const VT_VOLUME: flatbuffers::VOffsetT = 14;
  pub const VT_TURNOVER: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    KlineData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KlineDataArgs
  ) -> flatbuffers::WIPOffset<KlineData<'bldr>> {
    let mut builder = KlineDataBuilder::new(_fbb);
    builder.add_turnover(args.turnover);
    builder.add_volume(args.volume);
    builder.add_close(args.close);
    builder.add_low(args.low);
    builder.add_high(args.high);
    builder.add_open(args.open);
    builder.add_timestamp(args.timestamp);
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(KlineData::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn open(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_OPEN, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn high(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_HIGH, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn low(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_LOW, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn close(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_CLOSE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn volume(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_VOLUME, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn turnover(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(KlineData::VT_TURNOVER, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for KlineData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<f64>("open", Self::VT_OPEN, false)?
     .visit_field::<f64>("high", Self::VT_HIGH, false)?
     .visit_field::<f64>("low", Self::VT_LOW, false)?
     .visit_field::<f64>("close", Self::VT_CLOSE, false)?
     .visit_field::<f64>("volume", Self::VT_VOLUME, false)?
     .visit_field::<f64>("turnover", Self::VT_TURNOVER, false)?
     .finish();
    Ok(())
  }
}
pub struct KlineDataArgs {
    pub timestamp: u64,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub turnover: f64,
}
impl<'a> Default for KlineDataArgs {
  #[inline]
  fn default() -> Self {
    KlineDataArgs {
      timestamp: 0,
      open: 0.0,
      high: 0.0,
      low: 0.0,
      close: 0.0,
      volume: 0.0,
      turnover: 0.0,
    }
  }
}

pub struct KlineDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> KlineDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: u64) {
    self.fbb_.push_slot::<u64>(KlineData::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_open(&mut self, open: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_OPEN, open, 0.0);
  }
  #[inline]
  pub fn add_high(&mut self, high: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_HIGH, high, 0.0);
  }
  #[inline]
  pub fn add_low(&mut self, low: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_LOW, low, 0.0);
  }
  #[inline]
  pub fn add_close(&mut self, close: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_CLOSE, close, 0.0);
  }
  #[inline]
  pub fn add_volume(&mut self, volume: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_VOLUME, volume, 0.0);
  }
  #[inline]
  pub fn add_turnover(&mut self, turnover: f64) {
    self.fbb_.push_slot::<f64>(KlineData::VT_TURNOVER, turnover, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> KlineDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KlineDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<KlineData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for KlineData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("KlineData");
      ds.field("timestamp", &self.timestamp());
      ds.field("open", &self.open());
      ds.field("high", &self.high());
      ds.field("low", &self.low());
      ds.field("close", &self.close());
      ds.field("volume", &self.volume());
      ds.field("turnover", &self.turnover());
      ds.finish()
  }
}
pub enum KlineArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KlineArray<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for KlineArray<'a> {
  type Inner = KlineArray<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> KlineArray<'a> {
  pub const VT_DATA: flatbuffers::VOffsetT = 4;
  pub const VT_SYMBOL: flatbuffers::VOffsetT = 6;
  pub const VT_INTERVAL: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    KlineArray { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KlineArrayArgs<'args>
  ) -> flatbuffers::WIPOffset<KlineArray<'bldr>> {
    let mut builder = KlineArrayBuilder::new(_fbb);
    if let Some(x) = args.interval { builder.add_interval(x); }
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    if let Some(x) = args.data { builder.add_data(x); }
    builder.finish()
  }


  #[inline]
  pub fn data(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<KlineData<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<KlineData>>>>(KlineArray::VT_DATA, None)}
  }
  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(KlineArray::VT_SYMBOL, None)}
  }
  #[inline]
  pub fn interval(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(KlineArray::VT_INTERVAL, None)}
  }
}

impl flatbuffers::Verifiable for KlineArray<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<KlineData>>>>("data", Self::VT_DATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("interval", Self::VT_INTERVAL, false)?
     .finish();
    Ok(())
  }
}
pub struct KlineArrayArgs<'a> {
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<KlineData<'a>>>>>,
    pub symbol: Option<flatbuffers::WIPOffset<&'a str>>,
    pub interval: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for KlineArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    KlineArrayArgs {
      data: None,
      symbol: None,
      interval: None,
    }
  }
}

pub struct KlineArrayBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> KlineArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<KlineData<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(KlineArray::VT_DATA, data);
  }
  #[inline]
  pub fn add_symbol(&mut self, symbol: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(KlineArray::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_interval(&mut self, interval: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(KlineArray::VT_INTERVAL, interval);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> KlineArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KlineArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<KlineArray<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for KlineArray<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("KlineArray");
      ds.field("data", &self.data());
      ds.field("symbol", &self.symbol());
      ds.field("interval", &self.interval());
      ds.finish()
  }
}
pub enum CalculationResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CalculationResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CalculationResult<'a> {
  type Inner = CalculationResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CalculationResult<'a> {
  pub const VT_SMA: flatbuffers::VOffsetT = 4;
  pub const VT_EMA: flatbuffers::VOffsetT = 6;
  pub const VT_RSI: flatbuffers::VOffsetT = 8;
  pub const VT_MACD: flatbuffers::VOffsetT = 10;
  pub const VT_BOLLINGER_UPPER: flatbuffers::VOffsetT = 12;
  pub const VT_BOLLINGER_LOWER: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CalculationResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CalculationResultArgs<'args>
  ) -> flatbuffers::WIPOffset<CalculationResult<'bldr>> {
    let mut builder = CalculationResultBuilder::new(_fbb);
    if let Some(x) = args.bollinger_lower { builder.add_bollinger_lower(x); }
    if let Some(x) = args.bollinger_upper { builder.add_bollinger_upper(x); }
    if let Some(x) = args.macd { builder.add_macd(x); }
    if let Some(x) = args.rsi { builder.add_rsi(x); }
    if let Some(x) = args.ema { builder.add_ema(x); }
    if let Some(x) = args.sma { builder.add_sma(x); }
    builder.finish()
  }


  #[inline]
  pub fn sma(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_SMA, None)}
  }
  #[inline]
  pub fn ema(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_EMA, None)}
  }
  #[inline]
  pub fn rsi(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_RSI, None)}
  }
  #[inline]
  pub fn macd(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_MACD, None)}
  }
  #[inline]
  pub fn bollinger_upper(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_BOLLINGER_UPPER, None)}
  }
  #[inline]
  pub fn bollinger_lower(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(CalculationResult::VT_BOLLINGER_LOWER, None)}
  }
}

impl flatbuffers::Verifiable for CalculationResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("sma", Self::VT_SMA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("ema", Self::VT_EMA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("rsi", Self::VT_RSI, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("macd", Self::VT_MACD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("bollinger_upper", Self::VT_BOLLINGER_UPPER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("bollinger_lower", Self::VT_BOLLINGER_LOWER, false)?
     .finish();
    Ok(())
  }
}
pub struct CalculationResultArgs<'a> {
    pub sma: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub ema: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub rsi: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub macd: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub bollinger_upper: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub bollinger_lower: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for CalculationResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    CalculationResultArgs {
      sma: None,
      ema: None,
      rsi: None,
      macd: None,
      bollinger_upper: None,
      bollinger_lower: None,
    }
  }
}

pub struct CalculationResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CalculationResultBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sma(&mut self, sma: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_SMA, sma);
  }
  #[inline]
  pub fn add_ema(&mut self, ema: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_EMA, ema);
  }
  #[inline]
  pub fn add_rsi(&mut self, rsi: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_RSI, rsi);
  }
  #[inline]
  pub fn add_macd(&mut self, macd: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_MACD, macd);
  }
  #[inline]
  pub fn add_bollinger_upper(&mut self, bollinger_upper: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_BOLLINGER_UPPER, bollinger_upper);
  }
  #[inline]
  pub fn add_bollinger_lower(&mut self, bollinger_lower: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CalculationResult::VT_BOLLINGER_LOWER, bollinger_lower);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CalculationResultBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CalculationResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CalculationResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CalculationResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CalculationResult");
      ds.field("sma", &self.sma());
      ds.field("ema", &self.ema());
      ds.field("rsi", &self.rsi());
      ds.field("macd", &self.macd());
      ds.field("bollinger_upper", &self.bollinger_upper());
      ds.field("bollinger_lower", &self.bollinger_lower());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `KlineArray`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kline_array_unchecked`.
pub fn root_as_kline_array(buf: &[u8]) -> Result<KlineArray, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<KlineArray>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `KlineArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_kline_array_unchecked`.
pub fn size_prefixed_root_as_kline_array(buf: &[u8]) -> Result<KlineArray, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<KlineArray>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `KlineArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kline_array_unchecked`.
pub fn root_as_kline_array_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KlineArray<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<KlineArray<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `KlineArray` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kline_array_unchecked`.
pub fn size_prefixed_root_as_kline_array_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KlineArray<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<KlineArray<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a KlineArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `KlineArray`.
pub unsafe fn root_as_kline_array_unchecked(buf: &[u8]) -> KlineArray {
  flatbuffers::root_unchecked::<KlineArray>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed KlineArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `KlineArray`.
pub unsafe fn size_prefixed_root_as_kline_array_unchecked(buf: &[u8]) -> KlineArray {
  flatbuffers::size_prefixed_root_unchecked::<KlineArray>(buf)
}
pub const KLINE_ARRAY_IDENTIFIER: &str = "KLI1";

#[inline]
pub fn kline_array_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, KLINE_ARRAY_IDENTIFIER, false)
}

#[inline]
pub fn kline_array_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, KLINE_ARRAY_IDENTIFIER, true)
}

#[inline]
pub fn finish_kline_array_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<KlineArray<'a>>) {
  fbb.finish(root, Some(KLINE_ARRAY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_kline_array_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<KlineArray<'a>>) {
  fbb.finish_size_prefixed(root, Some(KLINE_ARRAY_IDENTIFIER));
}
}  // pub mod Kline

