// 文件路径: app/api/v2/users/[userId]/reset-password/route.ts
// 描述: 管理员为用户重置密码 (Admin resets a user's password)

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { Prisma } from '@prisma/client'; // Only Prisma namespace needed for error type
import bcrypt from 'bcrypt';
// import crypto from 'crypto'; // No longer auto-generating password
// import { JWTUtils } from '@/lib/auth/oauth2'; // REMOVED
import { requirePermission, AuthenticatedRequest } from '@/lib/auth/middleware'; // 引入 requirePermission


const MIN_PASSWORD_LENGTH = 8;
// const AUTOGENERATED_PASSWORD_LENGTH = 12; // REMOVED

// --- 辅助函数 (Copied/adapted) ---
function errorResponse(message: string, status: number, errorCode?: string) {
  return NextResponse.json({ error: errorCode || 'request_failed', message }, { status });
}

// isUserAdmin function is no longer needed.
// generateRandomPassword function is no longer needed.


interface RouteContext {
  params: {
    userId: string; // 目标用户的ID (ID of the target user)
  };
}

interface ResetPasswordRequestBody {
  newPassword: string;
}

// --- POST /api/v2/users/{userId}/reset-password (管理员重置用户密码) ---
async function adminResetPasswordHandler(req: AuthenticatedRequest, context: RouteContext) {
  const { params } = context;
  const targetUserId = params.userId;
  const performingAdmin = req.user;

  console.log(`Admin user ${performingAdmin?.id} (ClientID: ${performingAdmin?.clientId}) attempting to RESET PASSWORD for user ${targetUserId}.`);

  // 1. 解析请求体 (Parse request body) - Was step 2
  let requestBody: ResetPasswordRequestBody;
  try {
    requestBody = await req.json();
  } catch (e) {
    return errorResponse('无效的JSON请求体 (Invalid JSON request body).', 400, 'invalid_request_body');
  }

  const { newPassword } = requestBody;

  // 2. 验证新密码 (Validate new password) - Was part of step 3 & 4
  if (!newPassword || typeof newPassword !== 'string') {
    return errorResponse('必须提供新密码 "newPassword"。(New password "newPassword" must be provided and be a string.)', 400, 'validation_error_newPassword_required');
  }
  if (newPassword.length < MIN_PASSWORD_LENGTH) {
    return errorResponse(`新密码必须至少包含 ${MIN_PASSWORD_LENGTH} 个字符。(New password must be at least ${MIN_PASSWORD_LENGTH} characters long.)`, 400, 'password_too_short');
  }
  // TODO: 集成真实的密码策略服务 (Integrate actual password policy service for more complex checks)
  // Example: const policyCheck = await passwordPolicyService.validate(newPassword, targetUserId);
  // if (!policyCheck.isValid) {
  //   return errorResponse(`新密码不符合策略: ${policyCheck.message}`, 400, 'password_policy_violation');
  // }


  try {
    // 3. 检查目标用户是否存在 (Check if target user exists) - Was step 5
    const userToUpdate = await prisma.user.findUnique({ where: { id: targetUserId } });
    if (!userToUpdate) return errorResponse('用户未找到，无法重置密码。(User not found to reset password.)', 404, 'user_not_found');

    // (可选) 防止管理员通过此特定流程重置自己的密码，如果适用
    // if (targetUserId === performingAdmin?.id) {
    //   return errorResponse('管理员不能通过此接口重置自己的密码。请使用账户管理中的修改密码功能。', 400, 'self_reset_not_allowed');
    // }

    // 4. 哈希新密码并更新用户 (Hash new password and update user) - Was step 6
    const newPasswordHash = await bcrypt.hash(newPassword, 10);

    await prisma.$transaction(async (tx) => {
      // a. 更新用户密码和状态 (Update user's password and status)
      await tx.user.update({
        where: { id: targetUserId },
        data: {
          passwordHash: newPasswordHash,
          mustChangePassword: true, // 强制用户在下次登录时修改密码 (Force user to change password on next login)
          failedLoginAttempts: 0,   // 重置登录尝试 (Reset login attempts)
          lockedUntil: null,        // 解锁账户 (Unlock account)
          updatedAt: new Date(),
        },
      });

      // b. 将新密码哈希添加到历史记录 (Add new password hash to history)
      await tx.passwordHistory.create({
        data: {
          userId: targetUserId,
          passwordHash: newPasswordHash,
        },
      });
    });

    console.log(`Password for user ${targetUserId} has been reset by admin ${performingAdmin?.id}. User must change it on next login.`);

    // 5. 返回成功响应 (Return success response) - Was step 7
    return new NextResponse(null, { status: 204 }); // 204 No Content is appropriate

  } catch (error: any) {
    console.error(`管理员 ${performingAdmin?.id} 在为用户 ${targetUserId} 重置密码时出错: (Error resetting password for user ${targetUserId} by admin ${performingAdmin?.id}:)`, error);
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === 'P2025') { // Record to update not found
        return errorResponse('用户未找到，无法重置密码。(User not found, cannot reset password.)', 404, 'user_not_found_on_update');
      }
    }
    return errorResponse('重置用户密码时发生意外错误。(An unexpected error occurred while resetting user password.)', 500, 'server_error');
  }
}
export const POST = requirePermission('users:password:reset', adminResetPasswordHandler);
