apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  labels:
    app: ts-next-template
    environment: dev
  name: mysql-pv-new
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /var/lib/docker/data/mysql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem 