apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2  # 123456
  MYSQL_DATABASE: ZGF0YWFsY2hlbWlzdA==  # dataalchemist
  MYSQL_USER: cm9vdA==                  # root
  MYSQL_PASSWORD: MTIzNDU2              # 123456 