// 文件路径: app/api/v2/auth/register/route.ts
// 描述: 管理员创建新用户端点 (Admin creates new user endpoint)

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { Prisma } from '@prisma/client'; // Prisma types, User type not directly used
import bcrypt from 'bcrypt';
// import { verifyV2SessionAccessToken, V2AccessTokenPayload } from '@/lib/auth/v2AuthUtils'; // REMOVED
import { isValidEmail } from '@/lib/utils'; // Assuming a utility for email validation
import { requirePermission, AuthenticatedRequest } from '@/lib/auth/middleware'; // 引入 requirePermission (Import requirePermission)

// 模拟的管理员用户ID列表或角色检查逻辑 (Simulated admin user ID list or role check logic)
// 在实际应用中，这应该是一个更健壮的RBAC检查 (In a real application, this should be a more robust RBAC check)
// This will be handled by requirePermission now.
// const ADMIN_USER_IDS = ['cluser1test123456789012345']; // Example admin user ID
// const REQUIRED_ROLE_FOR_REGISTRATION = 'admin'; // Or a specific permission needed

// 辅助函数：错误响应 (Helper function: Error response)
function errorResponse(message: string, status: number, errorCode?: string) {
  return NextResponse.json({ error: errorCode || 'registration_failed', message }, { status });
}

// 使用 requirePermission 包装原始的 POST 处理函数
// (Wrap the original POST handler with requirePermission)
// The 'event' parameter is not strictly needed here for basic Next.js route handlers but included for HOF consistency
async function registerUserHandler(req: AuthenticatedRequest, event?: any) {
  // 管理员认证和权限检查已由 requirePermission 处理
  // (Admin authentication and permission check is handled by requirePermission)
  // req.user now contains the OAuth Access Token payload for the admin
  const adminUser = req.user;
  console.log(`Admin (ID: ${adminUser?.id}, ClientID: ${adminUser?.clientId}) is registering a new user (permission 'auth:register' granted).`);

  // 1. 解析请求体 (Parse request body) - (Was step 2)
  let requestBody;
  try {
    requestBody = await req.json();
  } catch (e) {
    return errorResponse('Invalid JSON request body.', 400, 'invalid_request');
  }

  const {
    username, email, password,
    firstName, lastName, displayName, avatar, phone,
    organization, department, workLocation,
    isActive = true, // 默认为激活状态 (Defaults to active)
    mustChangePassword = true, // 默认需要修改密码 (Defaults to must change password)
  } = requestBody;

  // 3. 输入数据验证 (Input data validation)
  if (!username || !email || !password) {
    return errorResponse('Username, email, and password are required.', 400, 'validation_error');
  }
  if (password.length < 8) { // 密码最小长度示例 (Example: minimum password length)
    return errorResponse('Password must be at least 8 characters long.', 400, 'validation_error');
  }
  if (!isValidEmail(email)) { // 使用假设的工具函数验证邮箱格式 (Use assumed utility function to validate email format)
      return errorResponse('Invalid email format.', 400, 'validation_error');
  }

  try {
    // 4. 检查用户名或邮箱是否已存在 (Check if username or email already exists)
    const existingUser = await prisma.user.findFirst({
      where: { OR: [{ username: username.trim() }, { email: email.trim().toLowerCase() }] },
    });
    if (existingUser) {
      const conflictField = existingUser.username === username.trim() ? 'username' : 'email';
      return errorResponse(`${conflictField} already exists.`, 409, 'conflict');
    }

    // 5. 安全地哈希密码 (Securely hash the password)
    const passwordHash = await bcrypt.hash(password, 10); // 10 is the salt rounds

    // 6. 创建新用户记录 (Create new User record)
    const newUser = await prisma.user.create({
      data: {
        username: username.trim(),
        email: email.trim().toLowerCase(),
        passwordHash,
        firstName: firstName || null,
        lastName: lastName || null,
        displayName: displayName || username.trim(), // 默认使用 username作为 displayName
        avatar: avatar || null,
        phone: phone || null,
        organization: organization || null,
        department: department || null,
        workLocation: workLocation || null,
        isActive: Boolean(isActive),
        mustChangePassword: Boolean(mustChangePassword),
        failedLoginAttempts: 0,
        // createdAt, updatedAt are auto-generated by Prisma
        // lastLoginAt, lockedUntil default to null
      },
    });

    // 7. 构建并返回响应 (Construct and return response)
    // 不应返回 passwordHash 或其他敏感内部字段 (Should not return passwordHash or other sensitive internal fields)
    const userResponse = {
      id: newUser.id,
      username: newUser.username,
      email: newUser.email,
      firstName: newUser.firstName,
      lastName: newUser.lastName,
      displayName: newUser.displayName,
      avatar: newUser.avatar,
      phone: newUser.phone,
      organization: newUser.organization,
      department: newUser.department,
      workLocation: newUser.workLocation,
      isActive: newUser.isActive,
      mustChangePassword: newUser.mustChangePassword,
      createdAt: newUser.createdAt,
      updatedAt: newUser.updatedAt,
    };

    return NextResponse.json(userResponse, { status: 201 }); // 201 Created

  } catch (error: any) {
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      // 处理 Prisma 特定的已知请求错误 (Handle Prisma-specific known request errors)
      if (error.code === 'P2002') { // Unique constraint failed
        const target = (error.meta?.target as string[]) || ['field'];
        return errorResponse(`Conflict: The ${target.join(', ')} you entered is already in use.`, 409, 'conflict');
      }
    }
    console.error('User registration error by admin:', adminUser?.id, error); // 使用从req.user获取的adminId
    return errorResponse('An unexpected error occurred during user registration.', 500, 'server_error');
  }
}

// 将包装后的处理函数导出为 POST
// (Export the wrapped handler as POST)
export const POST = requirePermission('auth:register')(registerUserHandler);

// 确保 JWTUtils.verifyV2AuthAccessToken 和 isValidEmail 存在
// (Ensure JWTUtils.verifyV2AuthAccessToken and isValidEmail exist) - NO LONGER NEEDED for JWTUtils
// 这些声明帮助TypeScript识别这些外部函数，实际实现应在各自的文件中。
// (These declarations help TypeScript recognize these external functions; actual implementations should be in their respective files.)
/*
declare module '@/lib/utils' { // Assuming isValidEmail is still in lib/utils
  export function isValidEmail(email: string): boolean;
}
*/
// User type is not explicitly used in this file, Prisma types are used for operations.
