apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-next-template-config
data:
  # MySQL 连接配置
  MYSQL_HOST: 'mysql'
  MYSQL_PORT: '3306'
  MYSQL_USER: 'root'
  MYSQL_DATABASE: 'dataalchemist'
  # 添加其他应用配置
  NODE_ENV: 'production'
  NEXT_TELEMETRY_DISABLED: '1'
  PORT: '3000'
  HOSTNAME: '0.0.0.0'
  # Scheduler API 配置
  SCHEDULER_API_URL: 'http://scheduler-service:8080'
