apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-next-template
  labels:
    app: ts-next-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ts-next-template
  template:
    metadata:
      labels:
        app: ts-next-template
    spec:
      containers:
        - name: ts-next-template
          image: liushuodocker/ts-next:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: MYSQL_DATABASE
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: NODE_ENV
            - name: NEXT_TELEMETRY_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: NEXT_TELEMETRY_DISABLED
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: PORT
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: ts-next-template-config
                  key: HOSTNAME
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
