apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - db-secret.yaml
  - scheduler-secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: ts-next-template
  app.kubernetes.io/part-of: ts-next-template
  app.kubernetes.io/managed-by: kustomize 