apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/deployment.yaml
  - app/service.yaml
  - app/ingress.yaml
  - app/pvc.yaml
  - app/configmap.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - mysql/pvc.yaml
  - mysql/secret.yaml
