apiVersion: v1
kind: ResourceQuota
metadata:
  name: ts-next-template-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
    services.loadbalancers: "1"
    services.nodeports: "0" 