/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** N-API SDK 配置 (N-API SDK Configuration) */
export interface NapiSdkConfig {
  baseUrl: string
  timeout?: number
  retryCount?: number
  retryDelay?: number
  debug?: boolean
}
/**
 * 创建 OAuth SDK 实例 (Create OAuth SDK Instance)
 *
 * # Arguments
 * * `config` - SDK 配置 (SDK Configuration)
 *
 * # Returns
 * * `Result<NapiOAuthSDK>` - SDK 实例或错误 (SDK Instance or Error)
 */
export declare function createSdk(config: NapiSdkConfig): NapiOAuthSDK
export type NapiOAuthSDK = NapiOAuthSdk
/** N-API OAuth SDK 封装类 (N-API OAuth SDK Wrapper) */
export class NapiOAuthSdk {
  /**
   * 用户登录 (User Login)
   *
   * # Arguments
   * * `username` - 用户名 (Username)
   * * `password` - 密码 (Password)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 登录响应数据 (Login Response Data)
   */
  authLogin(username: string, password: string): Promise<any>
  /**
   * 用户登出 (User Logout)
   *
   * # Returns
   * * `Result<bool>` - 登出是否成功 (Logout Success)
   */
  authLogout(): Promise<boolean>
  /**
   * 刷新访问令牌 (Refresh Access Token)
   *
   * # Arguments
   * * `refresh_token` - 刷新令牌 (Refresh Token)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 新的令牌对数据 (New Token Pair Data)
   */
  tokenRefresh(refreshToken: string): Promise<any>
  /**
   * 获取用户信息 (Get User Info)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 用户信息数据 (User Info Data)
   */
  userGetInfo(): Promise<any>
  /**
   * 验证令牌 (Introspect Token)
   *
   * # Arguments
   * * `token` - 要验证的令牌 (Token to Introspect)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 令牌信息 (Token Info)
   */
  tokenIntrospect(token: string): Promise<any>
  /**
   * 撤销令牌 (Revoke Token)
   *
   * # Arguments
   * * `token` - 要撤销的令牌 (Token to Revoke)
   *
   * # Returns
   * * `Result<bool>` - 撤销是否成功 (Revocation Success)
   */
  tokenRevoke(token: string): Promise<boolean>
  /**
   * 更新用户信息 (Update User Profile)
   *
   * # Arguments
   * * `data` - 用户数据 (User Profile Data)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 更新后的用户信息 (Updated User Info)
   */
  userUpdateProfile(data: any): Promise<any>
  /**
   * 获取权限列表 (Get Permissions List)
   *
   * # Arguments
   * * `page` - 页码 (Page Number)
   * * `page_size` - 每页大小 (Page Size)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 权限列表数据 (Permissions List Data)
   */
  rbacGetPermissions(page?: number | undefined | null, pageSize?: number | undefined | null): Promise<any>
  /**
   * 获取角色列表 (Get Roles List)
   *
   * # Arguments
   * * `page` - 页码 (Page Number)
   * * `page_size` - 每页大小 (Page Size)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 角色列表数据 (Roles List Data)
   */
  rbacGetRoles(page?: number | undefined | null, pageSize?: number | undefined | null): Promise<any>
  /**
   * 为用户分配角色 (Assign Role to User)
   *
   * # Arguments
   * * `user_id` - 用户ID (User ID)
   * * `role_id` - 角色ID (Role ID)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 分配结果数据 (Assignment Result Data)
   */
  rbacAssignRole(userId: string, roleId: string): Promise<any>
  /**
   * 撤销用户角色 (Revoke Role from User)
   *
   * # Arguments
   * * `user_id` - 用户ID (User ID)
   * * `role_id` - 角色ID (Role ID)
   *
   * # Returns
   * * `Result<bool>` - 撤销是否成功 (Revocation Success)
   */
  rbacRevokeRole(userId: string, roleId: string): Promise<boolean>
  /**
   * 获取客户端列表 (Get Client List)
   *
   * # Arguments
   * * `page` - 页码 (Page Number)
   * * `page_size` - 每页大小 (Page Size)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 客户端列表数据 (Client List Data)
   */
  clientList(page?: number | undefined | null, pageSize?: number | undefined | null): Promise<any>
  /**
   * 获取客户端详情 (Get Client Details)
   *
   * # Arguments
   * * `client_id` - 客户端ID (Client ID)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 客户端详情数据 (Client Details Data)
   */
  clientGet(clientId: string): Promise<any>
  /**
   * 获取审计日志 (Get Audit Logs)
   *
   * # Arguments
   * * `page` - 页码 (Page Number)
   * * `page_size` - 每页大小 (Page Size)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 审计日志数据 (Audit Logs Data)
   */
  auditGetLogs(page?: number | undefined | null, pageSize?: number | undefined | null): Promise<any>
  /**
   * 获取用户审计日志 (Get User Audit Logs)
   *
   * # Arguments
   * * `user_id` - 用户ID (User ID)
   * * `page` - 页码 (Page Number)
   * * `page_size` - 每页大小 (Page Size)
   *
   * # Returns
   * * `Result<serde_json::Value>` - 审计日志数据 (Audit Logs Data)
   */
  auditGetUserLogs(userId: string, page?: number | undefined | null, pageSize?: number | undefined | null): Promise<any>
}
