// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KlineData } from './kline-data';

export class KlineArray {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): KlineArray {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsKlineArray(bb: flatbuffers.ByteBuffer, obj?: KlineArray): KlineArray {
    return (obj || new KlineArray()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsKlineArray(bb: flatbuffers.ByteBuffer, obj?: KlineArray): KlineArray {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new KlineArray()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean {
    return bb.__has_identifier('KLI1');
  }

  data(index: number, obj?: KlineData): KlineData | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? (obj || new KlineData()).__init(
          this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4),
          this.bb!
        )
      : null;
  }

  dataLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  symbol(): string | null;
  symbol(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  symbol(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  interval(): string | null;
  interval(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  interval(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startKlineArray(builder: flatbuffers.Builder) {
    builder.startObject(3);
  }

  static addData(builder: flatbuffers.Builder, dataOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, dataOffset, 0);
  }

  static createDataVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startDataVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4);
  }

  static addSymbol(builder: flatbuffers.Builder, symbolOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, symbolOffset, 0);
  }

  static addInterval(builder: flatbuffers.Builder, intervalOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, intervalOffset, 0);
  }

  static endKlineArray(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static finishKlineArrayBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset, 'KLI1');
  }

  static finishSizePrefixedKlineArrayBuffer(
    builder: flatbuffers.Builder,
    offset: flatbuffers.Offset
  ) {
    builder.finish(offset, 'KLI1', true);
  }

  static createKlineArray(
    builder: flatbuffers.Builder,
    dataOffset: flatbuffers.Offset,
    symbolOffset: flatbuffers.Offset,
    intervalOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    KlineArray.startKlineArray(builder);
    KlineArray.addData(builder, dataOffset);
    KlineArray.addSymbol(builder, symbolOffset);
    KlineArray.addInterval(builder, intervalOffset);
    return KlineArray.endKlineArray(builder);
  }
}
