apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-next-template-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ts-next-template.local  # 本地开发环境使用
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: ts-next-template-service
                port:
                  number: 80 