apiVersion: v1
kind: Service
metadata:
  name: ts-next-template-service
  labels:
    app: ts-next-template
spec:
  type: ClusterIP

  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: ts-next-template
