/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Node.js Logger binding */
export declare class Logger {
  /** Create a new Logger instance */
  constructor(serverAddress: string)
  /** Log an info message */
  info(message: string): void
  /** Log an error message */
  error(message: string): void
  /** Log a warning message */
  warn(message: string): void
  /** Log a debug message */
  debug(message: string): void
  /** Log a trace message */
  trace(message: string): void
  /** Log a message with structured fields */
  logWithFields(level: string, message: string, fieldsJson?: string | undefined | null, tags?: Array<string> | undefined | null): void
  /** Log a message with trace ID */
  logWithTrace(level: string, message: string, traceId: string, fieldsJson?: string | undefined | null): void
  /** Check connection status */
  isConnected(): boolean
  /** Get client stats */
  getStats(): ClientStats
}
/** Client stats */
export declare class ClientStats {
  isConnected: boolean
}
