/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_klineprocess_free: (a: number, b: number) => void;
export const klineprocess_new: (a: any, b: number, c: number) => [number, number, number];
export const klineprocess_set_canvases: (a: number, b: any, c: any, d: any) => [number, number];
export const klineprocess_draw_all: (a: number) => [number, number];
export const klineprocess_handle_mouse_move: (a: number, b: number, c: number) => void;
export const klineprocess_get_cursor_style: (a: number, b: number, c: number) => [number, number];
export const klineprocess_handle_mouse_leave: (a: number) => number;
export const klineprocess_handle_wheel: (a: number, b: number, c: number, d: number) => void;
export const klineprocess_handle_mouse_down: (a: number, b: number, c: number) => number;
export const klineprocess_handle_mouse_up: (a: number, b: number, c: number) => number;
export const klineprocess_handle_mouse_drag: (a: number, b: number, c: number) => void;
export const klineprocess_set_render_mode: (a: number, b: number, c: number) => [number, number];
export const klineprocess_handle_click: (a: number, b: number, c: number) => number;
export const klineprocess_set_config_json: (a: number, b: number, c: number) => [number, number];
export const klineprocess_handle_canvas_resize: (a: number, b: number, c: number) => void;
export const klineprocess_update_config: (a: number, b: any) => [number, number];
export const klineprocess_get_config: (a: number) => [number, number, number];
export const klineprocess_get_theme: (a: number) => [number, number, number];
export const start: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
