name: Build Base Docker Image

on:
  push:
    branches: ['main']
    paths:
      - 'Dockerfile.base'
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile.base'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 22.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile.base') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: liushuodocker/ts-next-template-base:${{ env.NODE_VERSION }},liushuodocker/ts-next-template-base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
