name: Docker Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly module
        run: |
          cd wasm-cal
          chmod +x build.sh
          ./build.sh

      - name: Upload WebAssembly build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: wasm-cal/pkg

  build-app:
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download WebAssembly build artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: public/wasm-cal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build-docker/Dockerfile
          push: true
          tags: |
            liushuodocker/ts-next:latest
            liushuodocker/ts-next:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
